// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
)

type Affected struct {
	AffectedID int64  `db:"affected_id" json:"affectedId"`
	EntityType string `db:"entity_type" json:"entityType"`
}

type AffectedCpe struct {
	AffectedID      int64          `db:"affected_id" json:"affectedId"`
	VulnerabilityID int64          `db:"vulnerability_id" json:"vulnerabilityId"`
	Type            string         `db:"type" json:"type"`
	Vendor          sql.NullString `db:"vendor" json:"vendor"`
	Product         string         `db:"product" json:"product"`
	Version         sql.NullString `db:"version" json:"version"`
	Update          sql.NullString `db:"update" json:"update"`
	TargetSoftware  sql.NullString `db:"target_software" json:"targetSoftware"`
}

type AffectedDistroPackage struct {
	AffectedID      int64  `db:"affected_id" json:"affectedId"`
	VulnerabilityID int64  `db:"vulnerability_id" json:"vulnerabilityId"`
	PackageName     string `db:"package_name" json:"packageName"`
	OsID            int64  `db:"os_id" json:"osId"`
}

type AffectedPackage struct {
	AffectedID      int64          `db:"affected_id" json:"affectedId"`
	VulnerabilityID sql.NullInt64  `db:"vulnerability_id" json:"vulnerabilityId"`
	Ecosystem       sql.NullString `db:"ecosystem" json:"ecosystem"`
	PackageName     sql.NullString `db:"package_name" json:"packageName"`
	Purl            sql.NullString `db:"purl" json:"purl"`
}

type AffectedSeverity struct {
	AffectedSeverityID int64          `db:"affected_severity_id" json:"affectedSeverityId"`
	AffectedID         int64          `db:"affected_id" json:"affectedId"`
	Type               string         `db:"type" json:"type"`
	Score              string         `db:"score" json:"score"`
	Source             sql.NullString `db:"source" json:"source"`
	Tag                sql.NullString `db:"tag" json:"tag"`
}

type AffectedVersion struct {
	VersionID  int64  `db:"version_id" json:"versionId"`
	AffectedID int64  `db:"affected_id" json:"affectedId"`
	Version    string `db:"version" json:"version"`
}

type Alias struct {
	AliasID         int64  `db:"alias_id" json:"aliasId"`
	VulnerabilityID int64  `db:"vulnerability_id" json:"vulnerabilityId"`
	Alias           string `db:"alias" json:"alias"`
}

type DatabaseSpecific struct {
	DbSpecificID int64  `db:"db_specific_id" json:"dbSpecificId"`
	EntityType   string `db:"entity_type" json:"entityType"`
}

type DatabaseSpecificNvd struct {
	DbSpecificID          int64          `db:"db_specific_id" json:"dbSpecificId"`
	Vulnstatus            sql.NullString `db:"vulnstatus" json:"vulnstatus"`
	Cisaexploitadd        sql.NullString `db:"cisaexploitadd" json:"cisaexploitadd"`
	Cisaactiondue         sql.NullString `db:"cisaactiondue" json:"cisaactiondue"`
	Cisarequiredaction    sql.NullString `db:"cisarequiredaction" json:"cisarequiredaction"`
	Cisavulnerabilityname sql.NullString `db:"cisavulnerabilityname" json:"cisavulnerabilityname"`
}

type DbMetadatum struct {
	BuildTimestamp string `db:"build_timestamp" json:"buildTimestamp"`
	SchemaVersion  int64  `db:"schema_version" json:"schemaVersion"`
}

type Description struct {
	Digest string `db:"digest" json:"digest"`
	Value  string `db:"value" json:"value"`
}

type LogicalPackage struct {
	LogicalPackageID int64 `db:"logical_package_id" json:"logicalPackageId"`
	AffectedID       int64 `db:"affected_id" json:"affectedId"`
}

type NotAffectedVersion struct {
	VersionID  int64  `db:"version_id" json:"versionId"`
	AffectedID int64  `db:"affected_id" json:"affectedId"`
	Version    string `db:"version" json:"version"`
}

type OperatingSystem struct {
	OsID         int64          `db:"os_id" json:"osId"`
	Name         string         `db:"name" json:"name"`
	MajorVersion string         `db:"major_version" json:"majorVersion"`
	MinorVersion sql.NullString `db:"minor_version" json:"minorVersion"`
	Codename     sql.NullString `db:"codename" json:"codename"`
}

type PackageDigest struct {
	VulnerabilityID int64  `db:"vulnerability_id" json:"vulnerabilityId"`
	DigestAlgorithm string `db:"digest_algorithm" json:"digestAlgorithm"`
	DigestValue     string `db:"digest_value" json:"digestValue"`
}

type PackageQualifier struct {
	QualifierID int64         `db:"qualifier_id" json:"qualifierId"`
	AffectedID  sql.NullInt64 `db:"affected_id" json:"affectedId"`
	EntityType  string        `db:"entity_type" json:"entityType"`
}

type PackageQualifierPlatformCpe struct {
	QualifierID int64  `db:"qualifier_id" json:"qualifierId"`
	Cpe         string `db:"cpe" json:"cpe"`
}

type PackageQualifierRpmModularity struct {
	QualifierID int64  `db:"qualifier_id" json:"qualifierId"`
	Module      string `db:"module" json:"module"`
}

type Provider struct {
	ProviderID        int64          `db:"provider_id" json:"providerId"`
	Name              string         `db:"name" json:"name"`
	Version           sql.NullString `db:"version" json:"version"`
	DateCaptured      sql.NullString `db:"date_captured" json:"dateCaptured"`
	InputDigest       sql.NullString `db:"input_digest" json:"inputDigest"`
	DataOciRepository sql.NullString `db:"data_oci_repository" json:"dataOciRepository"`
}

type RangeEvent struct {
	EventID      int64          `db:"event_id" json:"eventId"`
	AffectedID   int64          `db:"affected_id" json:"affectedId"`
	Type         string         `db:"type" json:"type"`
	Repo         sql.NullString `db:"repo" json:"repo"`
	Introduced   sql.NullString `db:"introduced" json:"introduced"`
	Fixed        sql.NullString `db:"fixed" json:"fixed"`
	LastAffected sql.NullString `db:"last_affected" json:"lastAffected"`
	Limit        sql.NullString `db:"limit" json:"limit"`
	State        sql.NullString `db:"state" json:"state"`
}

type References struct {
	ReferenceID     int64  `db:"reference_id" json:"referenceId"`
	VulnerabilityID int64  `db:"vulnerability_id" json:"vulnerabilityId"`
	Type            string `db:"type" json:"type"`
	Url             string `db:"url" json:"url"`
}

type RelatedVulnerability struct {
	RelatedID              int64  `db:"related_id" json:"relatedId"`
	VulnerabilityID        int64  `db:"vulnerability_id" json:"vulnerabilityId"`
	RelatedVulnerabilityID string `db:"related_vulnerability_id" json:"relatedVulnerabilityId"`
}

type Severity struct {
	SeverityID      int64          `db:"severity_id" json:"severityId"`
	VulnerabilityID int64          `db:"vulnerability_id" json:"vulnerabilityId"`
	Type            string         `db:"type" json:"type"`
	Score           string         `db:"score" json:"score"`
	Source          sql.NullString `db:"source" json:"source"`
	Tag             sql.NullString `db:"tag" json:"tag"`
}

type Vulnerability struct {
	VulnerabilityID    int64          `db:"vulnerability_id" json:"vulnerabilityId"`
	ProviderID         int64          `db:"provider_id" json:"providerId"`
	ID                 string         `db:"id" json:"id"`
	Modified           sql.NullString `db:"modified" json:"modified"`
	Published          sql.NullString `db:"published" json:"published"`
	Withdrawn          sql.NullString `db:"withdrawn" json:"withdrawn"`
	SummaryDigest      sql.NullString `db:"summary_digest" json:"summaryDigest"`
	DetailDigest       sql.NullString `db:"detail_digest" json:"detailDigest"`
	DatabaseSpecificID sql.NullInt64  `db:"database_specific_id" json:"databaseSpecificId"`
}
