# only pull in version updates that were released more than a week ago (low-pass filter for quickly-retracted releases)
cooldown: 7d
# note: we inherit tool definitions from anchore/go-make's embedded .binny.yaml, so we only
# need to specify tools here that are not already defined there (or that we want to override
# with different versions).
tools:
  # used for integration tests
  - name: skopeo
    version:
      want: v1.23.0
    method: go-install
    with:
      module: github.com/containers/skopeo
      entrypoint: cmd/skopeo
      args:
        - "-tags"
        - containers_image_openpgp
      env:
        - CGO_ENABLED=0
        - GO_DYN_FLAGS=""
