permit:
  - BSD.*
  - MIT.*
  - Apache.*
  - MPL.*
  - ISC
ignore-packages:
  # packageurl-go is released under the MIT license located in the root of the repo at /mit.LICENSE
  - github.com/anchore/packageurl-go

  # tools-golang is released under the Apache License, version 2.0 (Apache-2.0)
  # https://github.com/spdx/tools-golang/blob/main/LICENSE.code
  - github.com/spdx/tools-golang

  # from: https://github.com/xi2/xz/blob/master/LICENSE
  # All these files have been put into the public domain.
  # You can do whatever you want with these files.
  - github.com/xi2/xz

  # from: https://github.com/owenrumney/go-sarif/blob/main/LICENSE
  # This is released into the public domain using the "Unlicense license"
  - github.com/owenrumney/go-sarif/sarif
