permit:
  - BSD.*
  - MIT.*
  - Apache.*
  - MPL.*
  - ISC
ignore-packages:
  # packageurl-go is released under the MIT license located in the root of the repo at /mit.LICENSE
  - github.com/package-url/packageurl-go