version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: grype-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: grype
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Монтируем сгенерированный дамп из корня напрямую в initdb папку Postgres
      - ./vulnerability_postgres.sql:/docker-entrypoint-initdb.d/vulnerability_postgres.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d grype"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
