// DO NOT EDIT: generated by pkg/process/v6/transformers/internal/codename/main.go

package codename

var normalizedOSCodenames = map[string]map[string]map[string]string{
	"debian": {
		"1": {
			"1": "buzz",
			"2": "rex",
			"3": "bo",
		},
		"10": {"*": "buster"},
		"11": {"*": "bullseye"},
		"12": {"*": "bookworm"},
		"13": {"*": "trixie"},
		"2": {
			"0": "hamm",
			"1": "slink",
			"2": "potato",
		},
		"3": {
			"0": "woody",
			"1": "sarge",
		},
		"4": {"*": "etch"},
		"5": {"*": "lenny"},
		"6": {"*": "squeeze"},
		"7": {"*": "wheezy"},
		"8": {"*": "jessie"},
		"9": {"*": "stretch"},
	},
	"ubuntu": {
		"10": {
			"10": "maverick",
			"4":  "lucid",
		},
		"11": {
			"10": "oneiric",
			"4":  "natty",
		},
		"12": {
			"10": "quantal",
			"4":  "precise",
		},
		"13": {
			"10": "saucy",
			"4":  "raring",
		},
		"14": {
			"10": "utopic",
			"4":  "trusty",
		},
		"15": {
			"10": "wily",
			"4":  "vivid",
		},
		"16": {
			"10": "yakkety",
			"4":  "xenial",
		},
		"17": {
			"10": "artful",
			"4":  "zesty",
		},
		"18": {
			"10": "cosmic",
			"4":  "bionic",
		},
		"19": {
			"10": "eoan",
			"4":  "disco",
		},
		"20": {
			"10": "groovy",
			"4":  "focal",
		},
		"21": {
			"10": "impish",
			"4":  "hirsute",
		},
		"22": {
			"10": "kinetic",
			"4":  "jammy",
		},
		"23": {
			"10": "mantic",
			"4":  "lunar",
		},
		"24": {
			"10": "oracular",
			"4":  "noble",
		},
		"25": {
			"10": "questing",
			"4":  "plucky",
		},
		"4": {"10": "warty"},
		"5": {
			"10": "breezy",
			"4":  "hoary",
		},
		"6": {
			"10": "edgy",
			"6":  "dapper",
		},
		"7": {
			"10": "gutsy",
			"4":  "feisty",
		},
		"8": {
			"10": "intrepid",
			"4":  "hardy",
		},
		"9": {
			"10": "karmic",
			"4":  "jaunty",
		},
	},
}
