name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |-
            Hey :wave:! Welcome to the repo and thanks for reporting, we'll review this issue soon!
          pr-message: |-
            Hey :wave:! Welcome to the repo and thanks for your contribution, we'll review your PR soon!