name: "Validate GitHub Actions"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions: {}

jobs:
  zizmor:
    name: "Lint"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # for uploading SARIF results
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Run zizmor"
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          # there is a pass/fail gate as a repo ruleset (if there is no ruleset configured then the action will pass by default)
          advanced-security: true
          inputs: .github
